server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
    location /api/ {
        proxy_pass http://gost:18080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
    }
    location /save-config {
        proxy_pass http://config-saver:8888/cgi-bin/save;
        proxy_set_header Host $host;
    }
    location /ui/ {
        proxy_pass http://gost-ui-orig:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
